export const EVENT_OPTIONS = [
  "TOKEN2049 Dubai",
  "EthCC7",
  "BitcoinAsia",
  "NFT Bucharest",
  "Conf3rence",
  "dAppCon",
  "NFC Summit",
  "Consensus",
];

export const POSITION_OPTIONS = [
  "FOUNDER",
  "CO-FOUNDER",
  "INVESTOR",
  "CEO",
  "CTO",
  "CFO",
  "FINANCE MANAGER",
  "GENERAL MANAGER",
  "EVENT MANAGER",
  "PRODUCT MANAGER",
  "BLOCKCHAIN DEVELOPER",
  "SOLIDITY DEVELOPER",
  "DEVELOPER",
  "ENGINEER",
  "MARKETING",
  "INFLUENCER",
  "INTERN",
  "COMMUNITY MOD",
  "PRODUCT DESIGNER",
  "SALES MANAGER",
  "RESEARCHER",
  "SPACEHOST",
  "TRADER",
  "GAMING",
  "EDUCATOR",
  "ARTIST",
  "COLLAB MANAGER",
  "JOB SEEKING",
  "SUBCOMMUNITY",
  "CONTENT CREATOR",
  "TOKEN",
  "METAVERSE",
  "COMMUNITY",
  "HIRING",
  "BRANDING",
  "VALIDATOR",
  "INCUBATOR",
  "ACCELERATOR",
];

export const FIELD_OPTIONS = [
  "DEFI",
  "DePIN",
  "RWA",
  "GAMEFI",
  "TOKEN",
  "NFT",
  "AI",
  "EVENT",
  "DAO",
  "SOCIAL",
  "COMMUNITY",
  "TOKENIZATION",
  "BLOCKCHAIN",
  "Venture Capital",
  "INVESTMENT",
];

export const CITY_OPTIONS = [
  "Kathmandu",
  "Pokhara",
  "Lalitpur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Dharan",
  "Dhangadhi",
  "Butwal",
  "Hetauda",
  "Nepalganj",
  "Itahari",
  "Triyuga",
  "Godawari",
  "Gulariya",
  "Tulsipur",
  "Siddharthanagar",
  "Bhaktapur",
  "Dhankuta",
];
